version: '3'

services:
  db:
    container_name: postgres
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "GameDataBase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pg_data:
