version: '3'

services:
  db_api:
    container_name: postgres_backend_api
    image: postgres:16
    ports:
      - "5499:5432"
    environment:
      POSTGRES_DB: "ApiDataBase"
      POSTGRES_USER: "postgres_api"
      POSTGRES_PASSWORD: "postgres_api"
    volumes:
      - api_data:/var/lib/postgresql/data

  db_socket:
    container_name: postgres_backend_socket
    image: postgres:16
    ports:
      - "5498:5432"
    environment:
      POSTGRES_DB: "SocketDataBase"
      POSTGRES_USER: "postgres_socket"
      POSTGRES_PASSWORD: "postgres_socket"
    volumes:
      - socket_data:/var/lib/postgresql/data

  redis:
    container_name: redis_backend
    image: redis:7
    ports:
      - "6378:6379"

volumes:
  api_data:
  socket_data:
