### obtain game token properly
POST http://localhost:8000/game/game_token/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk5OTk2NDE2LCJpYXQiOjE2OTk5OTU4MTYsImp0aSI6ImU2YzY0ODUxNzE0YTQ2NzM4YjM2NTQwYWEzOTY5MzUzIiwidXNlcl9pZCI6IjQxYzhkN2I3LWRhMzktNDg4Zi04NDgwLWRlY2M1YzYwOWY4NyIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ._WobA1m3yOfG6-YzGQXbnUgXmFBHAXW7gb6rXA7kGy4

{
}
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk5OTk2NDE2LCJpYXQiOjE2OTk5OTU4MTYsImp0aSI6ImU2YzY0ODUxNzE0YTQ2NzM4YjM2NTQwYWEzOTY5MzUzIiwidXNlcl9pZCI6IjQxYzhkN2I3LWRhMzktNDg4Zi04NDgwLWRlY2M1YzYwOWY4NyIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ._WobA1m3yOfG6-YzGQXbnUgXmFBHAXW7gb6rXA7kGy4

### obtain game with no authentication
POST http://localhost:8000/game/game_token/
Content-Type: application/json

{
}

### get all tokens
GET http://localhost:8000/game/game_token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk5OTk2NzAyLCJpYXQiOjE2OTk5OTYxMDIsImp0aSI6IjYzNmE3YWY4NDVlNTQ0NGJhNmQ4MGI3Yzc1N2NiNDgwIiwidXNlcl9pZCI6IjM5NWQ1NDliLTliOTMtNGM5Zi05ODEwLTMyZDkzYzRhZjRiMSIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ.r6IM3ipsTFBL4hiljFyZGDT-JTU7_w96usD-5Xc3Ohs