### authenticate and get tokens
POST http://localhost:8000/users/token/
Content-Type: application/json

{
    "email": "michalski.44@wp.pl",
    "password":"123456PIOTR"
}

### refresh access token
POST http://localhost:8000/users/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY5ODA5NTU5NCwiaWF0IjoxNjk4MDkxOTk0LCJqdGkiOiJkZWU4NTQzNWM0ZGI0ZTczOWRhNmNiZTJjZDI2Yzg4MiIsInVzZXJfaWQiOiIzOTVkNTQ5Yi05YjkzLTRjOWYtOTgxMC0zMmQ5M2M0YWY0YjEiLCJpc3MiOiJQcm9jZW50YXVydXNTeXN0ZW1zIn0.0y7hctbRA_tMrEATaqzaSHRaCo4pz6hya4b8DVA-rYY"
}

### get all users
GET http://localhost:8000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA3NDYzLCJpYXQiOjE3MTQyMDY4NjMsImp0aSI6ImIzYWNlNzg0MTUyZjQ2YTBiNWM1NmFjNGViY2Q1ODU0IiwidXNlcl9pZCI6ImNmOGMwYTBjLTY0MWQtNDFhOC04NjhlLWQzMWQwNDlmODIxZCIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ.EHHe3rWSCidmhBVr2c_JV8gdBcvPCV0Y41KYC77n27g

### get users after filtering
GET http://localhost:8000/users/?username=ma
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA3NDYzLCJpYXQiOjE3MTQyMDY4NjMsImp0aSI6ImIzYWNlNzg0MTUyZjQ2YTBiNWM1NmFjNGViY2Q1ODU0IiwidXNlcl9pZCI6ImNmOGMwYTBjLTY0MWQtNDFhOC04NjhlLWQzMWQwNDlmODIxZCIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ.EHHe3rWSCidmhBVr2c_JV8gdBcvPCV0Y41KYC77n27g

### update user
PUT http://localhost:8000/users/cf8c0a0c-641d-41a8-868e-d31d049f821d/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0MjA4NzUzLCJpYXQiOjE3MTQyMDgxNTMsImp0aSI6IjgyYTMxOGJkYTBlYTQyOTJiYzA3YTRmZDU4ZmVjZWU0IiwidXNlcl9pZCI6ImNmOGMwYTBjLTY0MWQtNDFhOC04NjhlLWQzMWQwNDlmODIxZCIsImlzcyI6IlByb2NlbnRhdXJ1c1N5c3RlbXMifQ.zjDdqtkUPd-1nkzQzq7K2y8QyECbyhq88_C3CNSsWt8

{
    "phone_number": 776123660,
    "hide_contact_data": "True",
    "bio": ""
}